services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /home/nino/space-project:/var/www/html
      - /home/nino/space-project/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
    - app-network

  phpfpm:
    build: .
    env_file:
      - .env
    volumes:
      - /home/nino/space-project:/var/www/html
      - /home/nino/space-project/data:/var/www/html/data
    networks:
      - app-network

  jenkins:
    build: ./jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
        - jenkins_data:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/nino/jenkins-env:/env
    restart: always
    networks:
      - app-network

volumes:
  jenkins_data:


networks:
  app-network: